#!/usr/bin/env python3
"""Builds watcher/sources.json, the list of pages the watcher checks.

Two inputs, merged and de-duplicated by URL:

1. watcher/curated.json: agency landing pages and federal publications,
   picked by hand because they're where new versions get announced.
2. Every official URL cited as a source anywhere under data/ (the documents
   the engine's numbers were actually taken from), tagged with the data
   files that use it. "Official" means a .gov / .us / .mil host or one of
   the few official hosts on other domains listed in OFFICIAL_HOSTS.

Re-run after adding sources to data/ or curated.json:

    python watcher/build_sources.py
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.parse
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DATA = REPO / "data"
OFFICIAL_HOSTS = {"denvergov.org", "www.denvergov.org"}
# Hosts that reject automated requests outright. Checking them every day
# only produces noise; the curated list covers them another way or the gap
# is accepted.
SKIP_HOSTS: set[str] = set()


def is_official(url: str) -> bool:
    host = urllib.parse.urlsplit(url).netloc.lower().split(":")[0]
    if host in SKIP_HOSTS:
        return False
    return bool(re.search(r"\.(gov|us|mil)$", host)) or host in OFFICIAL_HOSTS


def jurisdiction_for(path: Path) -> str:
    rel = path.relative_to(DATA)
    if rel.parts[0] == "federal":
        return "US"
    m = re.match(r"([A-Z]{2})-", path.name)
    if m:
        return m.group(1)
    if path.name.startswith("federal"):
        return "US"
    return "US"


def source_id(jurisdiction: str, url: str) -> str:
    return f"{jurisdiction.lower()}-{hashlib.sha1(url.encode()).hexdigest()[:10]}"


def cited_sources() -> dict[str, dict]:
    found: dict[str, dict] = {}

    def walk(node, file: Path, title_hint: str | None):
        if isinstance(node, dict):
            title = node.get("title") if isinstance(node.get("title"), str) else title_hint
            for key, value in node.items():
                if key == "url" and isinstance(value, str) and value.startswith("http"):
                    url = value.strip()
                    if not is_official(url):
                        continue
                    entry = found.setdefault(url, {"jurisdiction": jurisdiction_for(file), "title": title,
                                                   "url": url, "used_by": []})
                    rel = str(file.relative_to(REPO))
                    if rel not in entry["used_by"]:
                        entry["used_by"].append(rel)
                    if not entry.get("title") and title:
                        entry["title"] = title
                else:
                    walk(value, file, title)
        elif isinstance(node, list):
            for item in node:
                walk(item, file, title_hint)

    for file in sorted(DATA.rglob("*.json")):
        try:
            walk(json.loads(file.read_text()), file, None)
        except json.JSONDecodeError as e:
            print(f"skipping {file}: {e}", file=sys.stderr)
    return found


def main() -> int:
    curated = json.loads((HERE / "curated.json").read_text())["sources"]
    cited = cited_sources()
    merged: dict[str, dict] = {}
    for s in curated:
        merged[s["url"]] = {**s, "origin": "curated"}
    for url, s in cited.items():
        if url in merged:
            merged[url]["used_by"] = s["used_by"]
        else:
            merged[url] = {**s, "origin": "data"}
    out = []
    for s in merged.values():
        s["id"] = source_id(s["jurisdiction"], s["url"])
        s.setdefault("title", None)
        out.append({k: s[k] for k in ("id", "jurisdiction", "title", "url", "kind", "origin", "used_by", "ignore",
                                      "contains") if s.get(k)})
    out.sort(key=lambda s: (s["jurisdiction"] != "US", s["jurisdiction"], s.get("title") or "", s["url"]))
    (HERE / "sources.json").write_text(json.dumps({
        "$comment": "Generated by watcher/build_sources.py from watcher/curated.json and the source URLs cited in data/. "
                    "Edit those, not this file. Optional per-source keys: 'kind': 'index' (also report added/removed "
                    "same-site links), 'ignore': [regex, ...] (drop matching lines), 'contains': 'start...end' "
                    "(only compare that stretch of the page).",
        "sources": out,
    }, indent=1) + "\n")
    print(f"{len(out)} sources ({sum(1 for s in out if s['origin'] == 'curated')} curated, "
          f"{sum(1 for s in out if s['origin'] == 'data')} cited in data/), "
          f"{len({s['jurisdiction'] for s in out})} jurisdictions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
