import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bundles every file under data/ into one importable Deno module,
 * supabase/functions/_shared/data-bundle.ts, keyed by the SAME
 * forward-slash-normalized relPath registry.ts's loadJson() looks up
 * (e.g. "states/AL-2026.json", "federal/2026.json").
 *
 * Why bundle instead of importing each JSON file directly: registry.ts
 * resolves which file to read at RUNTIME (loadJson(`states/${code}-${year}.json`)),
 * not via a static import path a bundler could discover on its own — a
 * Deno/Supabase Edge Function deployment can only include files it can
 * see referenced somewhere in the import graph, so this script generates
 * that one static reference covering all of them at once.
 *
 * Run this again — and redeploy the Edge Function — any time a file
 * under data/ changes. Nothing here reads data/ at request time; the
 * Edge Function only ever sees this generated snapshot.
 *
 *   node scripts/build-data-bundle.ts
 */

const HERE = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = join(HERE, '..');
const DATA_ROOT = join(REPO_ROOT, 'data');
const OUT_PATH = join(REPO_ROOT, 'supabase', 'functions', '_shared', 'data-bundle.ts');

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, out);
    } else if (entry.endsWith('.json')) {
      out.push(full);
    }
  }
  return out;
}

const files = walk(DATA_ROOT);
const bundle: Record<string, unknown> = {};
for (const full of files) {
  const relPath = relative(DATA_ROOT, full).replace(/\\/g, '/');
  bundle[relPath] = JSON.parse(readFileSync(full, 'utf8'));
}

const header =
  `// GENERATED by scripts/build-data-bundle.ts — do not hand-edit.\n` +
  `// Regenerate after any change under data/, then redeploy the Edge Function.\n` +
  `// Keyed by the same forward-slash relPath registry.ts's loadJson() uses.\n\n`;

const body = `export const DATA_BUNDLE: Record<string, unknown> = ${JSON.stringify(bundle)};\n`;

writeFileSync(OUT_PATH, header + body);
console.log(`Wrote ${files.length} files (${(Buffer.byteLength(header + body) / 1024).toFixed(0)} KB) to ${OUT_PATH}`);
